### ISSUE TITLE
Termbox does not start in LXC

### ISSUE THREAD

**Issue by edurenye** [nsf/termbox#106]
Termbox does not start in LXC with a TurnKeyLinux container, it gives the following error:
`consoleui failed: Failed to initialize terminal: termbox: error while reading terminfo data: termbox: unsupported terminal`
I connect throughout ssh and it works like a charm.

**Comment by nsf** [comment]
Termbox uses TERM environment variable to init for the right terminal. Termbox has a built-in database with commonly used terminals such as xterm, urxvt and few others. Also it support reading terminfo database which you need to install. It usually comes with ncurses packages. But you can play with TERM variable and see if your terminal is xterm compatible or not. E.g. `TERM=xterm ./yourapp`.

**Comment by edurenye** [comment]
Ok, so the problem is that LXC sets the $TERM variable to 'vt' + the id of the virtual container, when it is using bash actually. So this issue can be closed. Thank you!
