### ISSUE TITLE
Port https://github.com/nsf/termbox-go/issues/185

### ISSUE THREAD

**Issue by BrianOn99** [nsf/termbox#111]
On tiny we depends termbox, and there are archlinux users (including me) facing the same issue (see https://github.com/osa1/tiny/issues/86) as https://github.com/nsf/termbox-go/issues/185.

I guess it involves modifying https://github.com/nsf/termbox/blob/master/src/term.inl, but no idea how it is generated.

**Comment by nsf** [comment]
Also marked commit with tag `v1.1.1`, I guess it's somewhat important.

**Comment by osa1** [comment]
Thanks @nsf!

A correction: the downstream bug is https://github.com/osa1/tiny/issues/96.

**Comment by BrianOn99** [comment]
Thanks @nsf
