### ISSUE TITLE
Pressing ESC after setting the mode to TB_MOUSE_INPUT triggers assertion error

### ISSUE THREAD

**Issue by sru** [nsf/termbox#55]
It triggers [this assertion](https://github.com/nsf/termbox/blob/7c154d98a7d9207d768ee0a8e519ede74c0105cf/src/input.inl#L100).

The program is:
```
#include "termbox.h"

int main(int argc, char **argv) {
    tb_init();
    tb_select_input_mode(TB_INPUT_MOUSE);

    struct tb_event ev;
    tb_poll_event(&ev);

    tb_shutdown();
    return 0;
}
```

See also: gchp/rustbox#32

**Comment by nsf** [comment]
That's true. Because TB_INPUT_MOUSE is invalid input mode. It's a bit flag that should only be used in conjuction with TB_INPUT_ESC or TB_INPUT_ALT. I should enforce that I guess.

**Comment by sru** [comment]
Would it increase complexity to just add `TB_INPUT_MOUSE` mode if it's the only mode passed?

**Comment by nsf** [comment]
But what would it mean? No keyboard input? :) Initially there were two modes: ESC and ALT. And MOUSE is an additional mode which works with either of those.

**Comment by sru** [comment]
Hmm... I see. It was just a passing thought. Then does it make sense to lump MOUSE mode with the two keyboard modes (ESC and ALT)?

On the other thought, how are you going to enforce it?

**Comment by nsf** [comment]
I can make one of the modes a default one. Perhaps the one which is enabled by default. That is ESC mode. :)

**Comment by sru** [comment]
+1. You might want to make sure that if mouse mode is passed alone, the keyboard mode changes to ESC mode.

**Comment by panicbit** [comment]
What's the point of `TB_INPUT_CURRENT` then if you have to pass `TB_INPUT_ESC` or `TB_INPUT_ALT` anyway?

**Comment by sru** [comment]
https://github.com/nsf/termbox/blob/master/src/termbox.h#L237

It returns the current input mode.

**Comment by panicbit** [comment]
@nsf Can you think of any reason why I'm not getting the assertion using this C snippet (but i do get the assertion when using the Rust wrapper :frowning:)?
