### ISSUE TITLE
Mouse drag events

### ISSUE THREAD

**Issue by zyedidia** [nsf/termbox#69]
Is it possible to detect mouse drag events?

**Comment by nsf** [comment]
In [termbox-go](https://github.com/nsf/termbox-go), yes. In C version - no. I haven't ported all the fancy mouse code. C version of the termbox is very low priority for me. Consider using Go instead.

**Comment by zyedidia** [comment]
That's a shame. Is there any chance they might get implemented at some point?

**Comment by nsf** [comment]
Of course, but I wouldn't say this month. So, your best bet is to port it yourself.
