### ISSUE TITLE
termbox can't detect resize events when in select()

### ISSUE THREAD

**Issue by osa1** [nsf/termbox#71]
In my application I'm using `tb_poll_event()` in a `select()` loop. I'm calling `tb_poll_event()` only when stdin is ready. The problem is termbox can't detect resize events when I do that. As a test, if I remove my `select()` loop and use `tb_peek_event()`, it works fine. Note that I don't have any signal handlers for `SIGWINCH` or anything.

I thought of implementing my own `SIGWINCH` handler and calling termbox's `update_size()` but unfortunately that's a static functions so I can't do that.

Any ideas what may be causing this problem? Would it make sense to add a `tb_update_size()` function to manually trigger a resize in termbox?

Thanks.

**Comment by nsf** [comment]
Hm, it probably happens if both stdin and sigwinch were signalled. 

https://github.com/nsf/termbox/blob/master/src/termbox.c#L666-L685

Here I just return if one of them is ready, but I don't handle a case when both are ready. I'll think about a way to fix it. But if you can fix it yourself that'd be much nicer.

**Comment by osa1** [comment]
The code you pointed gave me ideas and I fixed this. Basically when `select()` fails, I'm calling `tb_peek_event()` with timeout 0. When `select()` fails because of a resize signal, termbox is returning a resize event. Awesome!

Thanks for the help.

**Comment by osa1** [comment]
It's still a bit sad that some events can get lost if termbox's event handlers are not called immediately...

**Comment by nsf** [comment]
Yes, ideally we need some sort of raw integration into event APIs like select.

My recomendation is to use Go version of the termbox instead and Go itself as well. If that's possible. It has a proper model for dealing with events and writing event-driven stuff there is super easy.
