### ISSUE TITLE
Tagged releases?

### ISSUE THREAD

**Issue by bfontaine** [nsf/termbox#82]
Hello,

The README mentions [versions](https://github.com/nsf/termbox#changes) (at least v1.0.0 for now); would it be possible to have git tags as well? GitHub automatically generates tarballs for tagged versions, allowing anyone to download e.g. `termbox` 1.0.0 with an URL like https://github.com/nsf/termbox/archive/v1.0.0.tar.gz.

Thanks!

**Comment by nsf** [comment]
Yeah sure, I'll tag it today or tomorrow.

**Comment by nsf** [comment]
https://github.com/nsf/termbox/tree/v1.0.0
https://github.com/nsf/termbox/tree/v1.1.0

Tags are here now, and 1.1.0 was kind of released, but I wouldn't make a big deal out of it. It's just here to mark some progress.

**Comment by bfontaine** [comment]
Thanks!
