### ISSUE TITLE
no mouse events in xterm and xfce4-terminal 

### ISSUE THREAD

**Issue by maep--** [nsf/termbox#87]
Using the termbox keyboard demo. The mouse events are reported as keyboard events, the reported key values appear to be random. Also, in xterm the box drawing characters are drawn as â. 

Arch Linux, xterm 325, xfce4-terminal 0.6.3, termbox trunk, $TERM = xterm

**Comment by nsf** [comment]
Hm, that's pretty weird, but I have no idea why it may happen.

**Comment by nsf** [comment]
Maybe non-utf8 locale? termbox assumes utf-8.

**Comment by maep--** [comment]
LANG is set to en_DK.utf8. I tried setting it to en_US.utf8 but no luck. Are there any other variables that could influence termbox/terminal behavior?

**Comment by nsf** [comment]
I fixed a bug just recently. Try updating? Reverted one of the commits.

**Comment by maep--** [comment]
That worked. Getting mouse events now.

**Comment by maep--** [comment]
Where are my manners? Thanks for the fix! :D
