### ISSUE TITLE
Feature request: scrolling with the mouse

### ISSUE THREAD

**Issue by SirCmpwn** [nsf/termbox#90]

**Comment by nsf** [comment]
Question though: I thought termbox can actually parse wheel up wheel down mouse events. So you can implement scrolling on your own. Not sure what you want here. Can you explain?

**Comment by SirCmpwn** [comment]
Oh, I see they come in as key events. I figured they'd come in as some sort of mouse event and didn't see that in the API.

**Comment by nsf** [comment]
Yeah, I think there is a "paint" demo program, see how it uses mouse, you can get mouse wheel events there just fine:

https://github.com/nsf/termbox/blob/master/src/demo/paint.c
