### ISSUE TITLE
Documentation: Termbox crystal-lang wrapper.

### ISSUE THREAD

**Issue by shayneoAtNorwood** [nsf/termbox#95]
Theres a wrapper here that works rather well, from my experiments

https://github.com/andrewsuzuki/termbox-crystal

Could this be added to the README.cr ?

**Comment by nsf** [comment]
I'm lazy, send a pull request.

**Comment by shayneoAtNorwood** [comment]
I think I've done this right.......
https://github.com/nsf/termbox/pull/96

**Comment by nsf** [comment]
Merged.
